// AUTO-GENERATED by scripts/fetch-sanity-data.mjs — DO NOT EDIT MANUALLY
// Last generated: 2026-07-29T01:26:47.433Z

export interface Artwork {
  id: string
  title: string
  category: string
  description: string
  story: string
  image: string
  images: string[]
  price: string | null
  medium: string
  size: string
  sizes: string[]
  year: string
  available: boolean
}

export const categories = [
  "All",
  "Originals",
  "Prints & Posters",
  "Commissions",
  "Home Decor",
  "Painted Bags",
  "Handmade Cards",
  "Painted Tees",
  "Portraits"
]

export const artworks: Artwork[] = [
  {
    "id": "maa-durga-divine-fury",
    "title": "Maa Durga — Divine Fury",
    "category": "Originals",
    "description": "A powerful charcoal and watercolor rendering of Maa Durga. Raw energy meets delicate detail in this large-format piece.",
    "story": "During Navratri, I was moved by the stories of Maa Durga — her fierce protection of the universe, her unwavering strength. This piece channels that divine feminine energy. The charcoal gives it raw power while the watercolor washes add a dreamlike quality, representing the balance between strength and grace.",
    "image": "https://lh3.googleusercontent.com/d/1Eqjxlph19X978jzZGMe1t4l8LqSaVl5b",
    "images": [
      "https://lh3.googleusercontent.com/d/1Eqjxlph19X978jzZGMe1t4l8LqSaVl5b",
      "https://lh3.googleusercontent.com/d/1q3mvpH5H6phAMJLLyiyx9p6L-R6FVFlT"
    ],
    "price": null,
    "medium": "Charcoal & Watercolor on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "lord-shiva-the-destroyer",
    "title": "Lord Shiva — The Destroyer",
    "category": "Originals",
    "description": "An intense acrylic and charcoal portrait of Lord Shiva in deep meditation. Blue tones and fierce strokes capture the cosmic energy of Mahadev.",
    "story": "Shiva has always fascinated me — the destroyer who is also the most compassionate. This painting captures that duality. The blue represents his cosmic form, while the charcoal strokes add an almost wild, untamable quality. Painting this felt like a meditation in itself.",
    "image": "https://lh3.googleusercontent.com/d/1hwX0uuQVUAxHxwpu5aBG0t_v4fn1w6RB",
    "images": [
      "https://lh3.googleusercontent.com/d/1hwX0uuQVUAxHxwpu5aBG0t_v4fn1w6RB",
      "https://lh3.googleusercontent.com/d/1h_kcDozhMIm4WG92tsvCv6NQXZTAtcMQ"
    ],
    "price": null,
    "medium": "Acrylic & Charcoal on Canvas",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "lord-ganesha-remover-of-obstacles",
    "title": "Lord Ganesha — Remover of Obstacles",
    "category": "Originals",
    "description": "A graceful depiction of Lord Ganesha in monochrome. Intricate details bring this beloved deity to life on canvas.",
    "story": "Ganesha is where every journey begins. I wanted this piece to feel gentle yet powerful — the monochrome palette strips away distraction and lets the form speak. Every curve and ornament was painted with reverence, a prayer in every brushstroke.",
    "image": "https://lh3.googleusercontent.com/d/1dDHqZzgsrGS-1gP4944zuKHor9FaJEYV",
    "images": [
      "https://lh3.googleusercontent.com/d/1dDHqZzgsrGS-1gP4944zuKHor9FaJEYV",
      "https://lh3.googleusercontent.com/d/1Y6T_5_MoxoyAYzuJueNbqgz6h2il9tcT"
    ],
    "price": null,
    "medium": "Acrylic on Canvas",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "lord-krishna-the-divine-flute",
    "title": "Lord Krishna — The Divine Flute",
    "category": "Originals",
    "description": "A watercolor and acrylic piece capturing Lord Krishna playing the divine flute. Soft colors and flowing composition evoke the melody of the cosmos.",
    "story": "Krishna's flute calls the soul home. This painting uses flowing watercolors to mirror the music — soft, ethereal, and endlessly beautiful. The golden tones represent divinity while the blues echo the infinite sky under which he played.",
    "image": "https://lh3.googleusercontent.com/d/1oOUE0mQ08hsXuhwmyskQE1CLJ1cs1h9D",
    "images": [
      "https://lh3.googleusercontent.com/d/1oOUE0mQ08hsXuhwmyskQE1CLJ1cs1h9D",
      "https://lh3.googleusercontent.com/d/1qBLqQVoQ1F2yNutLf8ZD7guti4S6gBPw"
    ],
    "price": null,
    "medium": "Watercolor & Acrylic on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "hanuman-the-devoted",
    "title": "Hanuman — The Devoted",
    "category": "Originals",
    "description": "A striking portrayal of Lord Hanuman in red and black. Bold strokes convey devotion, strength, and unwavering courage.",
    "story": "Hanuman ji embodies pure devotion and limitless strength. The red symbolizes his fierce loyalty, while the black charcoal adds raw intensity. This was one of the most emotionally charged pieces I have ever created — I could feel the energy as I painted.",
    "image": "https://lh3.googleusercontent.com/d/1fICzrwANPjkUNQ2YP-f4NAmUoZjYEDbO",
    "images": [
      "https://lh3.googleusercontent.com/d/1fICzrwANPjkUNQ2YP-f4NAmUoZjYEDbO",
      "https://lh3.googleusercontent.com/d/1msWfUnnnjDj5MonFydIg7WDDxij2gh9c"
    ],
    "price": null,
    "medium": "Acrylic & Charcoal on Canvas",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "lord-ram-maryada-purushottam",
    "title": "Lord Ram — Maryada Purushottam",
    "category": "Originals",
    "description": "A regal depiction of Lord Ram with bow and arrow. Earthy tones and detailed ornamentation showcase the ideal man and king.",
    "story": "Ram represents dharma — the ideal in every role. This painting focuses on his gentle strength, the quiet determination in his eyes. The earthy tones ground the divine in the human, reminding us that righteousness is a choice we make every day.",
    "image": "https://lh3.googleusercontent.com/d/1W9XC5mEI1UEMM6aX5RQNkmpG0VTCN_gf",
    "images": [
      "https://lh3.googleusercontent.com/d/1W9XC5mEI1UEMM6aX5RQNkmpG0VTCN_gf",
      "https://lh3.googleusercontent.com/d/1KpUKX7adNShSsLRdxJG930eqMQRAzUqi"
    ],
    "price": null,
    "medium": "Acrylic & Charcoal on Canvas",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "wild-horses-freedom-in-motion",
    "title": "Wild Horses — Freedom in Motion",
    "category": "Originals",
    "description": "A dynamic oil painting of wild horses galloping through golden light. Energy, freedom, and the raw beauty of nature captured on canvas.",
    "story": "Horses represent untamed freedom — the kind most of us only dream about. This painting captures that moment of pure motion, when muscle and wind become one. The golden light bathes them in warmth, as if nature itself is cheering them on.",
    "image": "https://lh3.googleusercontent.com/d/1uC-YjXcY7HX7ktI7jU0ODT7P8z4yXcQH",
    "images": [
      "https://lh3.googleusercontent.com/d/1uC-YjXcY7HX7ktI7jU0ODT7P8z4yXcQH",
      "https://lh3.googleusercontent.com/d/1GEmVUcFKpRc5CcITnrIre6YnmVpyZbVD"
    ],
    "price": null,
    "medium": "Oil on Canvas",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "autumn-serenity-forest-path",
    "title": "Autumn Serenity — Forest Path",
    "category": "Originals",
    "description": "A warm autumn landscape painting featuring a sunlit forest path. Golden leaves and soft light create a sense of peaceful solitude.",
    "story": "Autumn teaches us that letting go can be beautiful. This painting is about finding peace in change — the golden leaves falling, the light filtering through bare branches, the quiet path that invites you to walk and reflect.",
    "image": "https://lh3.googleusercontent.com/d/1nT22BcR8XTFeTKby1HXK-V0GpuXvM_mn",
    "images": [
      "https://lh3.googleusercontent.com/d/1nT22BcR8XTFeTKby1HXK-V0GpuXvM_mn",
      "https://lh3.googleusercontent.com/d/17VWbJBgzdkdqIGQSbCvRkIhDrxNLjb51",
      "https://lh3.googleusercontent.com/d/1_mVWjd-T_Z5oZwrAE1FvtNKEFXGlV73A"
    ],
    "price": null,
    "medium": "Acrylic on Canvas",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-maa-durga",
    "title": "Print — Maa Durga",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Maa Durga painting. Signed and archival.",
    "story": "A print for those who want to bring the energy of Maa Durga into their homes. Printed on premium archival paper with gallery-grade inks.",
    "image": "https://lh3.googleusercontent.com/d/1Eqjxlph19X978jzZGMe1t4l8LqSaVl5b",
    "images": [
      "https://lh3.googleusercontent.com/d/1Eqjxlph19X978jzZGMe1t4l8LqSaVl5b"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-lord-shiva",
    "title": "Print — Lord Shiva",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Lord Shiva painting. Signed and archival.",
    "story": "A print capturing the cosmic energy of Mahadev. Perfect for meditation spaces and living rooms.",
    "image": "https://lh3.googleusercontent.com/d/1hwX0uuQVUAxHxwpu5aBG0t_v4fn1w6RB",
    "images": [
      "https://lh3.googleusercontent.com/d/1hwX0uuQVUAxHxwpu5aBG0t_v4fn1w6RB"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-lord-ganesha",
    "title": "Print — Lord Ganesha",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Lord Ganesha painting. Signed and archival.",
    "story": "Bring the blessings of the remover of obstacles into your space with this premium art print.",
    "image": "https://lh3.googleusercontent.com/d/1dDHqZzgsrGS-1gP4944zuKHor9FaJEYV",
    "images": [
      "https://lh3.googleusercontent.com/d/1dDHqZzgsrGS-1gP4944zuKHor9FaJEYV"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-lord-krishna",
    "title": "Print — Lord Krishna",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Lord Krishna painting. Signed and archival.",
    "story": "The divine flute player in your space — a print that brings peace, beauty, and a touch of the divine.",
    "image": "https://lh3.googleusercontent.com/d/1oOUE0mQ08hsXuhwmyskQE1CLJ1cs1h9D",
    "images": [
      "https://lh3.googleusercontent.com/d/1oOUE0mQ08hsXuhwmyskQE1CLJ1cs1h9D"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-hanuman",
    "title": "Print — Hanuman",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Hanuman painting. Signed and archival.",
    "story": "The devotion and strength of Hanuman ji, now available as a premium art print for your home or office.",
    "image": "https://lh3.googleusercontent.com/d/1fICzrwANPjkUNQ2YP-f4NAmUoZjYEDbO",
    "images": [
      "https://lh3.googleusercontent.com/d/1fICzrwANPjkUNQ2YP-f4NAmUoZjYEDbO"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-lord-ram",
    "title": "Print — Lord Ram",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Lord Ram painting. Signed and archival.",
    "story": "The regal presence of Maryada Purushottam Ram in a premium art print, perfect for any devotional or living space.",
    "image": "https://lh3.googleusercontent.com/d/1W9XC5mEI1UEMM6aX5RQNkmpG0VTCN_gf",
    "images": [
      "https://lh3.googleusercontent.com/d/1W9XC5mEI1UEMM6aX5RQNkmpG0VTCN_gf"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-wild-horses",
    "title": "Print — Wild Horses",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Wild Horses painting. Signed and archival.",
    "story": "The freedom and energy of wild horses in a premium art print that brings movement and life to any wall.",
    "image": "https://lh3.googleusercontent.com/d/1uC-YjXcY7HX7ktI7jU0ODT7P8z4yXcQH",
    "images": [
      "https://lh3.googleusercontent.com/d/1uC-YjXcY7HX7ktI7jU0ODT7P8z4yXcQH"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "print-autumn-serenity",
    "title": "Print — Autumn Serenity",
    "category": "Prints & Posters",
    "description": "Museum-quality fine art print of the original Autumn Serenity painting. Signed and archival.",
    "story": "The peaceful beauty of an autumn forest path, now available as a premium art print.",
    "image": "https://lh3.googleusercontent.com/d/1nT22BcR8XTFeTKby1HXK-V0GpuXvM_mn",
    "images": [
      "https://lh3.googleusercontent.com/d/1nT22BcR8XTFeTKby1HXK-V0GpuXvM_mn"
    ],
    "price": null,
    "medium": "Archival Print on Paper",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "commission-horse-painting",
    "title": "Commission — Horse Painting",
    "category": "Commissions",
    "description": "Commission a custom horse painting tailored to your vision. Choose your style, size, and color palette.",
    "story": "Every commission begins with a conversation. Tell me about the horse you envision — wild and free, gentle and noble, or something entirely unique. Together we will create a piece that speaks to your heart.",
    "image": "https://lh3.googleusercontent.com/d/1uC-YjXcY7HX7ktI7jU0ODT7P8z4yXcQH",
    "images": [
      "https://lh3.googleusercontent.com/d/1uC-YjXcY7HX7ktI7jU0ODT7P8z4yXcQH",
      "https://lh3.googleusercontent.com/d/1GEmVUcFKpRc5CcITnrIre6YnmVpyZbVD"
    ],
    "price": null,
    "medium": "Your Choice of Medium",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "commission-lord-shiva-painting",
    "title": "Commission — Lord Shiva Painting",
    "category": "Commissions",
    "description": "Commission a custom Lord Shiva painting. Choose your preferred depiction, style, and medium.",
    "story": "Shiva can be depicted in countless forms — the meditating ascetic, the cosmic dancer, the loving husband. Tell me which aspect of Mahadev resonates with you, and I will bring that vision to life on canvas.",
    "image": "https://lh3.googleusercontent.com/d/1hwX0uuQVUAxHxwpu5aBG0t_v4fn1w6RB",
    "images": [
      "https://lh3.googleusercontent.com/d/1hwX0uuQVUAxHxwpu5aBG0t_v4fn1w6RB",
      "https://lh3.googleusercontent.com/d/1h_kcDozhMIm4WG92tsvCv6NQXZTAtcMQ"
    ],
    "price": null,
    "medium": "Your Choice of Medium",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "commission-autumn-landscape",
    "title": "Commission — Autumn Landscape",
    "category": "Commissions",
    "description": "Commission a custom autumn landscape painting. Perfect for bringing warmth and nature into your space.",
    "story": "Autumn landscapes are deeply personal — they reflect the viewer's own sense of nostalgia and peace. Whether you want a specific scene or a mood, I will create a landscape that feels like home.",
    "image": "https://lh3.googleusercontent.com/d/1nT22BcR8XTFeTKby1HXK-V0GpuXvM_mn",
    "images": [
      "https://lh3.googleusercontent.com/d/1nT22BcR8XTFeTKby1HXK-V0GpuXvM_mn",
      "https://lh3.googleusercontent.com/d/17VWbJBgzdkdqIGQSbCvRkIhDrxNLjb51"
    ],
    "price": null,
    "medium": "Your Choice of Medium",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "bird-paradise-wall-hanging",
    "title": "Bird Paradise — Wall Hanging",
    "category": "Home Decor",
    "description": "A hand-painted decorative wall hanging featuring colorful birds. Adds life and vibrancy to any room.",
    "story": "Birds represent freedom and joy. This wall hanging brings that energy into your living space — hand-painted with love, each bird is unique, just like the moments they represent.",
    "image": "https://lh3.googleusercontent.com/d/1dh08JTnsGADyRTS7kIPurFK8JaUFYT-D",
    "images": [
      "https://lh3.googleusercontent.com/d/1dh08JTnsGADyRTS7kIPurFK8JaUFYT-D",
      "https://lh3.googleusercontent.com/d/1bhbVl4M1X57e-n9OXI6ACLLDT0fPq8MP",
      "https://lh3.googleusercontent.com/d/1P8ZM9UxvGYaI-Kk6HSREP9Erll9FEe9l"
    ],
    "price": null,
    "medium": "Acrylic on Wood Panel",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "vintage-clock-wall-art",
    "title": "Vintage Clock — Wall Art",
    "category": "Home Decor",
    "description": "A hand-painted decorative wall piece featuring a vintage clock design. Functional art for your home.",
    "story": "Time is art. This wall piece merges the functional with the beautiful — a hand-painted clock design that turns your wall into a gallery.",
    "image": "https://lh3.googleusercontent.com/d/10VqB8sCPvj-d2G0SuOT-oHrmnI-_OPcW",
    "images": [
      "https://lh3.googleusercontent.com/d/10VqB8sCPvj-d2G0SuOT-oHrmnI-_OPcW",
      "https://lh3.googleusercontent.com/d/1yGwdhtnAuWFfernWtD-bOV0_iIMEEepM"
    ],
    "price": null,
    "medium": "Acrylic & Mixed Media on Board",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "hand-painted-decorative-pot",
    "title": "Hand-Painted Decorative Pot",
    "category": "Home Decor",
    "description": "A beautifully hand-painted terracotta pot. Perfect as a planter or decorative piece for your home.",
    "story": "A simple pot transformed into art. Hand-painted with intricate patterns and vibrant colors.",
    "image": "https://lh3.googleusercontent.com/d/1zihra7v9k4ijDksnzVHr_e5zC3cimWbM",
    "images": [
      "https://lh3.googleusercontent.com/d/1zihra7v9k4ijDksnzVHr_e5zC3cimWbM",
      "https://lh3.googleusercontent.com/d/1Ce14uTZTewIQxxUD1l7VnCdIfOsiesId"
    ],
    "price": null,
    "medium": "Acrylic on Terracotta",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "abstract-wall-hanging",
    "title": "Abstract Wall Hanging",
    "category": "Home Decor",
    "description": "A bold abstract wall hanging with vibrant textures and patterns. A statement piece for modern interiors.",
    "story": "Abstract art speaks where words fail. This wall hanging brings raw emotion and color into your space.",
    "image": "https://drive.google.com/thumbnail?id=1BEM_H2gn1rgjnEja3a809gycErCbmDEr&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=1BEM_H2gn1rgjnEja3a809gycErCbmDEr&sz=w1000",
      "https://drive.google.com/thumbnail?id=1CWESVbSwnTkbJ4nQxp1wI5aNR3A7o3y3&sz=w1000"
    ],
    "price": null,
    "medium": "Acrylic & Mixed Media on Board",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "evil-eye-wall-hanging",
    "title": "Evil Eye — Wall Hanging",
    "category": "Home Decor",
    "description": "A hand-painted evil eye wall hanging. A protective talisman and a stunning decorative piece for your home.",
    "story": "The evil eye is a symbol of protection and good fortune across cultures.",
    "image": "https://drive.google.com/thumbnail?id=1mP8PKoasDkfEuLk8nVYah7Z7i_bHXIF8&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=1mP8PKoasDkfEuLk8nVYah7Z7i_bHXIF8&sz=w1000"
    ],
    "price": null,
    "medium": "Acrylic on Wood Panel",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "floral-backpack",
    "title": "Floral Backpack",
    "category": "Painted Bags",
    "description": "A hand-painted backpack featuring a vibrant floral design. Functional wearable art for everyday use.",
    "story": "Why carry something ordinary when you can carry art? This backpack features hand-painted florals.",
    "image": "https://drive.google.com/thumbnail?id=1vXK5dWnq8KnNLVGEdyBvIKixvUOPpz0j&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=1vXK5dWnq8KnNLVGEdyBvIKixvUOPpz0j&sz=w1000",
      "https://lh3.googleusercontent.com/d/1z31sQzBYKakWaRt0T8PAF-kOAeclAezz",
      "https://lh3.googleusercontent.com/d/1XYChz0IYNcs9vxnQFo2d08WklAP_ra2w"
    ],
    "price": null,
    "medium": "Acrylic on Canvas Bag",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "artistic-handbag-design-1",
    "title": "Artistic Handbag — Design 1",
    "category": "Painted Bags",
    "description": "A structured handbag hand-painted with a unique artistic design. One-of-a-kind statement piece.",
    "story": "Every bag tells a story. This handbag was painted over several days, each brushstroke adding personality and flair.",
    "image": "https://lh3.googleusercontent.com/d/1uwgBSEXyr9bYjfEKDIieq1sJRUlI1uKj",
    "images": [
      "https://lh3.googleusercontent.com/d/1uwgBSEXyr9bYjfEKDIieq1sJRUlI1uKj",
      "https://lh3.googleusercontent.com/d/1KT5b_6H8nW6E2F3nlFtCR5yn3GW0gHlM"
    ],
    "price": null,
    "medium": "Acrylic on Faux Leather",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "artistic-handbag-design-2",
    "title": "Artistic Handbag — Design 2",
    "category": "Painted Bags",
    "description": "A hand-painted handbag with bold colors and artistic patterns.",
    "story": "Dark romance meets wearable art — this handbag features deep colors and expressive patterns painted by hand.",
    "image": "https://lh3.googleusercontent.com/d/1ujrQmgxTrsBtF00N5ispjZRq12186gRT",
    "images": [
      "https://lh3.googleusercontent.com/d/1ujrQmgxTrsBtF00N5ispjZRq12186gRT",
      "https://lh3.googleusercontent.com/d/136SLnk4Kr1oehRee9pFmodtxP_0qr9l0",
      "https://lh3.googleusercontent.com/d/1S_Bak6tgnuUQBMQcULSV7IzgDrPtSi8m"
    ],
    "price": null,
    "medium": "Acrylic on Faux Leather",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "artistic-handbag-design-3",
    "title": "Artistic Handbag — Design 3",
    "category": "Painted Bags",
    "description": "A beautifully crafted hand-painted handbag. Wearable art that stands out with every outfit.",
    "story": "Art is not just for walls — it belongs in your hands too.",
    "image": "https://lh3.googleusercontent.com/d/12Dqw6P1B5r__y-1JHmJyb7T3ijY0NeNF",
    "images": [
      "https://lh3.googleusercontent.com/d/12Dqw6P1B5r__y-1JHmJyb7T3ijY0NeNF",
      "https://lh3.googleusercontent.com/d/1C2PChD4ZKud5m_2n1slwezM6UUt97-fy"
    ],
    "price": null,
    "medium": "Acrylic on Faux Leather",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "handmade-greeting-card-design-1",
    "title": "Handmade Greeting Card — Design 1",
    "category": "Handmade Cards",
    "description": "A beautifully hand-illustrated greeting card. Perfect for birthdays, weddings, and special occasions.",
    "story": "In a world of mass-produced cards, a handmade one speaks volumes.",
    "image": "https://lh3.googleusercontent.com/d/1oQEYC_W91kzNGVptJ8zEs_5NPCWjUQHd",
    "images": [
      "https://lh3.googleusercontent.com/d/1oQEYC_W91kzNGVptJ8zEs_5NPCWjUQHd"
    ],
    "price": null,
    "medium": "Watercolor on Card Stock",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "handmade-greeting-card-design-2",
    "title": "Handmade Greeting Card — Design 2",
    "category": "Handmade Cards",
    "description": "A hand-painted greeting card with floral and golden accents.",
    "story": "Love deserves art. These cards feature hand-painted details with touches of color and texture.",
    "image": "https://lh3.googleusercontent.com/d/1Woi-cokISGV75VMnYOLB7iVC0GyLPUgr",
    "images": [
      "https://lh3.googleusercontent.com/d/1Woi-cokISGV75VMnYOLB7iVC0GyLPUgr"
    ],
    "price": null,
    "medium": "Watercolor & Ink on Card Stock",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "hand-painted-tee-design-1",
    "title": "Hand-Painted Tee — Design 1",
    "category": "Painted Tees",
    "description": "A one-of-a-kind hand-painted t-shirt. Wearable art that makes a bold statement.",
    "story": "Why wear something ordinary when you can wear art? Each tee is hand-painted with care.",
    "image": "https://drive.google.com/thumbnail?id=192WMfcOQ6NdwBUo19-K5FWDNj0oQ99oo&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=192WMfcOQ6NdwBUo19-K5FWDNj0oQ99oo&sz=w1000",
      "https://drive.google.com/thumbnail?id=15BaZ_7SZdgOSupc1tWJJ_-cBRo1p8Ear&sz=w1000",
      "https://drive.google.com/thumbnail?id=1vgGkQ0bROQ8f-NReokTlPmcJDnJRdjxE&sz=w1000"
    ],
    "price": null,
    "medium": "Fabric Paint on Cotton",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "portrait-style-1",
    "title": "Portrait — Style 1",
    "category": "Portraits",
    "description": "A beautifully crafted portrait capturing emotion and personality.",
    "story": "Every face tells a story. Portraits are my most intimate work.",
    "image": "https://drive.google.com/thumbnail?id=1Zbez5Hu1LWpE8v2CSmqNtaB9cJUhyqj2&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=1Zbez5Hu1LWpE8v2CSmqNtaB9cJUhyqj2&sz=w1000"
    ],
    "price": null,
    "medium": "Mixed Media",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "portrait-style-2",
    "title": "Portrait — Style 2",
    "category": "Portraits",
    "description": "A striking portrait with bold strokes and vivid detail.",
    "story": "Art transforms a simple photograph into something timeless.",
    "image": "https://drive.google.com/thumbnail?id=1o0knzsApUHlo86-MroDIbS4gnIOP9FSx&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=1o0knzsApUHlo86-MroDIbS4gnIOP9FSx&sz=w1000"
    ],
    "price": null,
    "medium": "Mixed Media",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  },
  {
    "id": "portrait-style-3",
    "title": "Portrait — Style 3",
    "category": "Portraits",
    "description": "A delicate portrait rendered with soft tones and fine detail.",
    "story": "Some moments deserve to be immortalized in art.",
    "image": "https://drive.google.com/thumbnail?id=1APincQmOO6ZVqWaxvHyC6lyCtH91idOC&sz=w1000",
    "images": [
      "https://drive.google.com/thumbnail?id=1APincQmOO6ZVqWaxvHyC6lyCtH91idOC&sz=w1000"
    ],
    "price": null,
    "medium": "Mixed Media",
    "size": "Customizable",
    "sizes": [
      "Customizable"
    ],
    "year": "2026",
    "available": true
  }
]
